---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.name" . }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "microservice.name" . }}-backend-config"}'
spec:
  selector:
    app: {{ include "microservice.name" . }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
---
